#!/bin/bash

L0=10  #▁
L1=20  #▂
L2=30  #▃
L3=40  #▄
L4=50  #▅
L5=60  #▆
L6=70  #▇
L7=80  #█

RED='\033[0;31m'
NC='\033[0m' # No Color

function bar() {
	if [ "$1" -lt "$L0" ]; then
		echo "▁";
	elif [ "$1" -lt "$L1" ]; then
		echo "▂";
	elif [ "$1" -lt "$L2" ]; then
		echo "▃";
	elif [ "$1" -lt "$L3" ]; then
		echo -e "▄";
	elif [ "$1" -lt "$L4" ]; then
		echo "▅";
	elif [ "$1" -lt "$L5" ]; then
		echo "▆";
	elif [ "$1" -lt "$L6" ]; then
		echo "▇";
	elif [ "$1" -lt "$L7" ]; then
		echo "█";
	else
		echo "!";
	fi
}

s=$(sensors | grep -E '^Core')

res=""

while IFS= read -r line; do
	temp=$(echo "$line" | awk '{print $3}' | sed -e 's/\+//g' -e 's/°C//g' -e 's/\..*//g')
	b=$(bar "$temp")
	res=${res}${b}
done <<< "$s"

echo "$res"

